config:
  - input:
      directory: /home/cameron/Projects
      formats:
        - PNG
        - JPEG
        - GIF
    output:
      directory: ~/Output
      outputformats:
        - PNG
        - JPEG
        - GIF
        - TIFF
  - input:
      directory: /somedir
      formats:
        - PNG
        - JPEG
        - GIF
    output:
      directory: ~/Output
      outputformats:
        - PNG
        - JPEG
        - GIF
